{
  "openapi": "3.1.0",
  "info": {
    "title": "API Documentation for jfapi-uat.infocloud.cc",
    "description": "自动生成的 API 文档",
    "version": "1.0.0"
  },
  "paths": {
    "/sys/getSysMenu": {
      "post": {
        "tags": [
          "sys"
        ],
        "summary": "getSysMenu",
        "description": "捕获于 2025-04-07 11:19:39",
        "operationId": "post_getSysMenu",
        "parameters": [
          {
            "name": "TOKEN",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "example": "603681e8-ba5b-4437-84cf-3804b315e8ee"
            },
            "description": "身份验证令牌"
          }
        ],
        "responses": {
          "200": {
            "description": "成功响应",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetsysmenuResponse"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/schemas/UnauthorizedError"
          },
          "422": {
            "$ref": "#/components/schemas/HTTPValidationError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GetsysmenuResponse": {
        "type": "object",
        "properties": {
          "errcode": {
            "type": "integer",
            "example": 200
          },
          "msg": {
            "type": "string",
            "example": "成功"
          },
          "code": {
            "type": "integer",
            "example": 200
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "example": "179"
                },
                "parentId": {
                  "type": "string",
                  "example": "0"
                },
                "name": {
                  "type": "string",
                  "example": "业务安全"
                },
                "url": {
                  "type": "string",
                  "example": ""
                },
                "level": {
                  "type": "integer",
                  "example": 1
                },
                "seq": {
                  "type": "integer",
                  "example": 0
                },
                "type": {
                  "type": "integer",
                  "example": 0
                },
                "component": {
                  "type": "null"
                },
                "status": {
                  "type": "integer",
                  "example": 1
                },
                "iconUrl": {
                  "type": "string",
                  "example": ""
                },
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "example": "180"
                      },
                      "parentId": {
                        "type": "string",
                        "example": "179"
                      },
                      "name": {
                        "type": "string",
                        "example": "信息安全"
                      },
                      "url": {
                        "type": "string",
                        "example": ""
                      },
                      "level": {
                        "type": "integer",
                        "example": 2
                      },
                      "seq": {
                        "type": "integer",
                        "example": 0
                      },
                      "type": {
                        "type": "integer",
                        "example": 0
                      },
                      "component": {
                        "type": "null"
                      },
                      "status": {
                        "type": "integer",
                        "example": 1
                      },
                      "iconUrl": {
                        "type": "string",
                        "example": ""
                      },
                      "children": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string",
                              "example": "192"
                            },
                            "parentId": {
                              "type": "string",
                              "example": "180"
                            },
                            "name": {
                              "type": "string",
                              "example": "敏感词管理"
                            },
                            "url": {
                              "type": "string",
                              "example": "/Base/sensitive"
                            },
                            "level": {
                              "type": "integer",
                              "example": 3
                            },
                            "seq": {
                              "type": "integer",
                              "example": 0
                            },
                            "type": {
                              "type": "integer",
                              "example": 0
                            },
                            "component": {
                              "type": "null"
                            },
                            "status": {
                              "type": "integer",
                              "example": 1
                            },
                            "iconUrl": {
                              "type": "string",
                              "example": ""
                            },
                            "children": {
                              "type": "array",
                              "items": {
                                "type": "string"
                              },
                              "example": []
                            }
                          }
                        },
                        "example": [
                          {
                            "id": "192",
                            "parentId": "180",
                            "name": "敏感词管理",
                            "url": "/Base/sensitive",
                            "level": 3,
                            "seq": 0,
                            "type": 0,
                            "component": null,
                            "status": 1,
                            "iconUrl": "",
                            "children": []
                          },
                          {
                            "id": "191",
                            "parentId": "180",
                            "name": "黑名单管理",
                            "url": "/Base/blacklist",
                            "level": 3,
                            "seq": 1,
                            "type": 0,
                            "component": null,
                            "status": 1,
                            "iconUrl": "",
                            "children": []
                          }
                        ]
                      }
                    }
                  },
                  "example": [
                    {
                      "id": "180",
                      "parentId": "179",
                      "name": "信息安全",
                      "url": "",
                      "level": 2,
                      "seq": 0,
                      "type": 0,
                      "component": null,
                      "status": 1,
                      "iconUrl": "",
                      "children": [
                        {
                          "id": "192",
                          "parentId": "180",
                          "name": "敏感词管理",
                          "url": "/Base/sensitive",
                          "level": 3,
                          "seq": 0,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "191",
                          "parentId": "180",
                          "name": "黑名单管理",
                          "url": "/Base/blacklist",
                          "level": 3,
                          "seq": 1,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        }
                      ]
                    },
                    {
                      "id": "218",
                      "parentId": "179",
                      "name": "模板管理",
                      "url": null,
                      "level": 2,
                      "seq": 1,
                      "type": 0,
                      "component": null,
                      "status": 1,
                      "iconUrl": "",
                      "children": [
                        {
                          "id": "219",
                          "parentId": "218",
                          "name": "人工模板审核",
                          "url": "/Base/manual-review",
                          "level": 3,
                          "seq": 0,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "220",
                          "parentId": "218",
                          "name": "模板审核记录",
                          "url": "/Base/audit-record",
                          "level": 3,
                          "seq": 1,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "221",
                          "parentId": "218",
                          "name": "模板审核策略配置",
                          "url": "/Base/strategy",
                          "level": 3,
                          "seq": 2,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "222",
                          "parentId": "218",
                          "name": "企业模板配置",
                          "url": "/Base/config",
                          "level": 3,
                          "seq": 3,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "223",
                          "parentId": "218",
                          "name": "企业模板列表",
                          "url": "/Base/template-manage",
                          "level": 3,
                          "seq": 4,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "471",
                          "parentId": "218",
                          "name": "自由发送白名单",
                          "url": "https://bizapi-uat.infocloud.cc/sheet-v2/scene/pcdatalist/h7t27fwrb6xxqz2t1phbh8z",
                          "level": 3,
                          "seq": 5,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "475",
                          "parentId": "218",
                          "name": "数据中心配置",
                          "url": "/Base/data-center",
                          "level": 3,
                          "seq": 6,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "476",
                          "parentId": "218",
                          "name": "签名审批",
                          "url": "/Base/signature-Approval",
                          "level": 3,
                          "seq": 7,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "478",
                          "parentId": "218",
                          "name": "签名审批查看",
                          "url": "/Base/signature-Approval-view",
                          "level": 3,
                          "seq": 8,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        },
                        {
                          "id": "477",
                          "parentId": "218",
                          "name": "企业签名同步",
                          "url": "/Base/signature-Sync",
                          "level": 3,
                          "seq": 9,
                          "type": 0,
                          "component": null,
                          "status": 1,
                          "iconUrl": "",
                          "children": []
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "example": [
              {
                "id": "179",
                "parentId": "0",
                "name": "业务安全",
                "url": "",
                "level": 1,
                "seq": 0,
                "type": 0,
                "component": null,
                "status": 1,
                "iconUrl": "",
                "children": [
                  {
                    "id": "180",
                    "parentId": "179",
                    "name": "信息安全",
                    "url": "",
                    "level": 2,
                    "seq": 0,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "192",
                        "parentId": "180",
                        "name": "敏感词管理",
                        "url": "/Base/sensitive",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "191",
                        "parentId": "180",
                        "name": "黑名单管理",
                        "url": "/Base/blacklist",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "218",
                    "parentId": "179",
                    "name": "模板管理",
                    "url": null,
                    "level": 2,
                    "seq": 1,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "219",
                        "parentId": "218",
                        "name": "人工模板审核",
                        "url": "/Base/manual-review",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "220",
                        "parentId": "218",
                        "name": "模板审核记录",
                        "url": "/Base/audit-record",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "221",
                        "parentId": "218",
                        "name": "模板审核策略配置",
                        "url": "/Base/strategy",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "222",
                        "parentId": "218",
                        "name": "企业模板配置",
                        "url": "/Base/config",
                        "level": 3,
                        "seq": 3,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "223",
                        "parentId": "218",
                        "name": "企业模板列表",
                        "url": "/Base/template-manage",
                        "level": 3,
                        "seq": 4,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "471",
                        "parentId": "218",
                        "name": "自由发送白名单",
                        "url": "https://bizapi-uat.infocloud.cc/sheet-v2/scene/pcdatalist/h7t27fwrb6xxqz2t1phbh8z",
                        "level": 3,
                        "seq": 5,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "475",
                        "parentId": "218",
                        "name": "数据中心配置",
                        "url": "/Base/data-center",
                        "level": 3,
                        "seq": 6,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "476",
                        "parentId": "218",
                        "name": "签名审批",
                        "url": "/Base/signature-Approval",
                        "level": 3,
                        "seq": 7,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "478",
                        "parentId": "218",
                        "name": "签名审批查看",
                        "url": "/Base/signature-Approval-view",
                        "level": 3,
                        "seq": 8,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "477",
                        "parentId": "218",
                        "name": "企业签名同步",
                        "url": "/Base/signature-Sync",
                        "level": 3,
                        "seq": 9,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "224",
                    "parentId": "179",
                    "name": "场景管理",
                    "url": null,
                    "level": 2,
                    "seq": 2,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "225",
                        "parentId": "224",
                        "name": "业务场景管理",
                        "url": "/Base/scene-manage",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "226",
                        "parentId": "224",
                        "name": "模板参数管理",
                        "url": "/Base/template-param-manage",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "455",
                        "parentId": "224",
                        "name": "回执错误码管理",
                        "url": "/Base/error-code-manage",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "283",
                    "parentId": "179",
                    "name": "活动分析",
                    "url": null,
                    "level": 2,
                    "seq": 3,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "284",
                        "parentId": "283",
                        "name": "短链报备审核",
                        "url": "/Base/short-audit",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "285",
                        "parentId": "283",
                        "name": "活动任务记录",
                        "url": "/Base/acttask",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "286",
                        "parentId": "283",
                        "name": "短信模板记录",
                        "url": "/Base/smstemplate",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "287",
                        "parentId": "283",
                        "name": "资源消耗查询",
                        "url": "/Base/sourcequota",
                        "level": 3,
                        "seq": 3,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "288",
                        "parentId": "283",
                        "name": "企业活动财务",
                        "url": "/Base/enterprise-actaccount",
                        "level": 3,
                        "seq": 4,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "293",
                        "parentId": "283",
                        "name": "活动签名审核",
                        "url": "/Base/sign-review",
                        "level": 3,
                        "seq": 5,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "294",
                    "parentId": "179",
                    "name": "数据统计",
                    "url": null,
                    "level": 2,
                    "seq": 4,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "295",
                        "parentId": "294",
                        "name": "客户新增分析",
                        "url": "/Base/customer-analysis",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "296",
                        "parentId": "294",
                        "name": "客户地域分布",
                        "url": "/Base/customer-distribution",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "298",
                        "parentId": "294",
                        "name": "短信发送量分析",
                        "url": "/Base/data-stats/analysis",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "299",
                        "parentId": "294",
                        "name": "短信发送趋势图",
                        "url": "/Base/data-stats/trend",
                        "level": 3,
                        "seq": 3,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "458",
                        "parentId": "294",
                        "name": "经分2.0统计",
                        "url": "/Base/jf-2.0-statistics",
                        "level": 3,
                        "seq": 4,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "466",
                    "parentId": "179",
                    "name": "短链审核",
                    "url": null,
                    "level": 2,
                    "seq": 5,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "467",
                        "parentId": "466",
                        "name": "短链审核列表",
                        "url": "/Base/short-review",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "468",
                        "parentId": "466",
                        "name": "短链审核记录",
                        "url": "/Base/short-record",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  }
                ]
              },
              {
                "id": "168",
                "parentId": "0",
                "name": "资源管理",
                "url": "",
                "level": 1,
                "seq": 1,
                "type": 0,
                "component": null,
                "status": 1,
                "iconUrl": "",
                "children": [
                  {
                    "id": "188",
                    "parentId": "168",
                    "name": "资源供应商管理",
                    "url": null,
                    "level": 2,
                    "seq": 0,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "189",
                        "parentId": "188",
                        "name": "供应商管理",
                        "url": "/Base/suppliers",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "185",
                    "parentId": "168",
                    "name": "资源管理",
                    "url": null,
                    "level": 2,
                    "seq": 1,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "186",
                        "parentId": "185",
                        "name": "资源分类管理",
                        "url": "/Base/classification",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "187",
                        "parentId": "185",
                        "name": "短信通道管理",
                        "url": "/Base/tunnel",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "431",
                        "parentId": "185",
                        "name": "通道组管理",
                        "url": "/Base/tunnelGroup",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "457",
                        "parentId": "185",
                        "name": "通道容器组管理",
                        "url": "/Base/cgroupManage",
                        "level": 3,
                        "seq": 3,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "182",
                    "parentId": "168",
                    "name": "接入尾号管理",
                    "url": null,
                    "level": 2,
                    "seq": 2,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "183",
                        "parentId": "182",
                        "name": "接入尾号列表",
                        "url": "/Base/tail-num-info",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "184",
                        "parentId": "182",
                        "name": "尾号配置记录",
                        "url": "/Base/record-tail-num",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "170",
                    "parentId": "168",
                    "name": "资源调度",
                    "url": null,
                    "level": 2,
                    "seq": 3,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "174",
                        "parentId": "170",
                        "name": "短信通道配置",
                        "url": "/Base/channel-config",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "175",
                        "parentId": "170",
                        "name": "业务调度策略",
                        "url": "/Base/channel-strategy",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "309",
                        "parentId": "170",
                        "name": "通道批量切换",
                        "url": "/Base/batch-switch",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "310",
                        "parentId": "170",
                        "name": "切换/还原记录",
                        "url": "/Base/switchback-show",
                        "level": 3,
                        "seq": 3,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "313",
                        "parentId": "170",
                        "name": "回执补发管理",
                        "url": "/Base/replace-manage",
                        "level": 3,
                        "seq": 4,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "169",
                    "parentId": "168",
                    "name": "资源成本管理",
                    "url": null,
                    "level": 2,
                    "seq": 4,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "171",
                        "parentId": "169",
                        "name": "通道成本",
                        "url": "/Base/cost-config-list",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "173",
                        "parentId": "169",
                        "name": "通道成本统计",
                        "url": "/Base/cost-manage",
                        "level": 3,
                        "seq": 1,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      },
                      {
                        "id": "311",
                        "parentId": "169",
                        "name": "企业成本统计",
                        "url": "/Base/ep-cost",
                        "level": 3,
                        "seq": 2,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "464",
                    "parentId": "168",
                    "name": "CMPP账号管理",
                    "url": null,
                    "level": 2,
                    "seq": 5,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "465",
                        "parentId": "464",
                        "name": "CMPP账号管理",
                        "url": "/Base/cmpp-manage",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "479",
                    "parentId": "168",
                    "name": "通道评价",
                    "url": null,
                    "level": 2,
                    "seq": 6,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "480",
                        "parentId": "479",
                        "name": "通道列表",
                        "url": "/Base/tunnel-eva-list",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "481",
                    "parentId": "168",
                    "name": "监控预警",
                    "url": null,
                    "level": 2,
                    "seq": 7,
                    "type": 0,
                    "component": null,
                    "status": 1,
                    "iconUrl": "",
                    "children": [
                      {
                        "id": "482",
                        "parentId": "481",
                        "name": "实时监控",
                        "url": "/Base/monitoring",
                        "level": 3,
                        "seq": 0,
                        "type": 0,
                        "component": null,
                        "status": 1,
                        "iconUrl": "",
                        "children": []
                      }
                    ]
                  }
                ]
              }
            ]
          },
          "errmsg": {
            "type": "string",
            "example": "成功"
          }
        }
      },
      "UnauthorizedError": {
        "type": "object",
        "properties": {
          "errcode": {
            "type": "integer",
            "example": 401
          },
          "message": {
            "type": "string",
            "example": "Unauthorized"
          }
        }
      },
      "HTTPValidationError": {
        "type": "object",
        "properties": {
          "errcode": {
            "type": "integer",
            "example": 422
          },
          "message": {
            "type": "string",
            "example": "Validation Error"
          }
        }
      }
    }
  }
}